---
ansible_python_interpreter: /usr/bin/python3
docker_composes:
  - name: wordpress
    pull: true
    definition:
      version: '3.3'
      services:
        db:
          image: mysql:5.7
          volumes:
            - db_data:/var/lib/mysql
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

        wordpress:
          depends_on:
            - db
          image: wordpress:latest
          ports:
            - "8000:80"
          restart: always
          environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
      volumes:
        db_data: {}

  - name: wordpress2
    state: absent
    definition:
      version: '3.3'
      services:
        db:
          image: mysql:5.7
          volumes:
            - db_data:/var/lib/mysql
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

        wordpress:
          depends_on:
            - db
          image: wordpress:latest
          ports:
            - "8000:80"
          restart: always
          environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
      volumes:
        db_data: {}

  - name: seafile-pro
    docker_login:
      registry_url: docker.seadrive.org
      username: seafile
      password: zjkmid6rQibdZ=uJMuWS
    definition:
      version: '2.0'
      services:
        db:
          restart: always
          image: mariadb:10.1
          environment:
            - MYSQL_ROOT_PASSWORD=seafile
            - MYSQL_LOG_CONSOLE=true
          networks:
            - seafile
        memcached:
          restart: always
          image: memcached:1.5.6
          entrypoint: memcached -m 256
          networks:
            - seafile
        elasticsearch:
          restart: always
          image: seafileltd/elasticsearch-with-ik:5.6.16
          environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          ulimits:
            memlock:
              soft: -1
              hard: -1
          mem_limit: 512m
          networks:
            - seafile
        seafile:
          restart: always
          image: docker.seadrive.org/seafileltd/seafile-pro-mc:8.0.9
          container_name: seafile_instance
          ports:
            - "3400:80"
            - "3401:8080"
          environment:
            - DB_HOST=db
            - DB_ROOT_PASSWD=seafile
            - TIME_ZONE=Europe/Vienna
            - SEAFILE_ADMIN_EMAIL=admin@seafile.com
            - SEAFILE_ADMIN_PASSWORD=seafile
            - SEAFILE_SERVER_LETSENCRYPT=false
            - SEAFILE_SERVER_HOSTNAME=seafile.com
          depends_on:
            - db
            - memcached
            - elasticsearch
          networks:
            - seafile
      networks:
        seafile:
